name: multi_image_picker
description: Flutter plugin that allows you to display multi image picker on iOS and Android.
version: 2.1.00
author: Radoslav Vitanov <radoslav.vitanov@icloud.com>
homepage: https://github.com/Sh1d0w/multi_image_picker

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.5

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.vitanov.multiimagepicker
    pluginClass: MultiImagePickerPlugin
environment:
    sdk: ">=2.0.0-dev.28.0 <3.0.0"
    flutter: ">=0.1.4 <2.0.0"